# numpy-基本功能

## 教學目標

這份教學的目標是介紹基本的 numpy 功能，並學習快速操作大量數值型態的資料。

## 適用對象

適用於有程式基礎，且擁有 python 基礎的學生。

若沒有先學過 python，請參考 [python-入門語法](./python-入門語法.ipynb) 教學。

## 執行時間

本教學全部執行時間約為 1.7527921199798584 秒。

|測試環境|名稱|
|-|-|
|主機板|X570 AORUS ELITE|
|處理器|AMD Ryzen 7 3700X 8-Core Processor|
|記憶體|Kingston KHX3200C16D4/16GX|
|硬碟|Seagate ST1000DM003-1ER1|
|顯示卡|GeForce RTX 2080|
|作業系統|Ubuntu 18.04 LTS|

## 大綱

- [簡介](#簡介)
- [安裝](#安裝)
- [陣列宣告](#陣列宣告)
- [陣列取值](#陣列取值)
- [陣列運算](#陣列運算)
- [創造陣列](#創造陣列)
- [矩陣運算](#矩陣運算)
- [維度運算](#維度運算)
- [練習](#練習)

## 簡介

根據 [Numpy 官方網站](https://numpy.org/)（v1.18）：

> NumPy is the fundamental package for scientific computing with Python.
> 
> NumPy 是設計用於進行科學計算的 Python 工具
> 
> It contains among other things:
>
> 包含了以下內容:
>
> - a powerful N-dimensional array object
>
> N 維度的矩陣運算功能
>
> - sophisticated (broadcasting) functions
>
> 方便的運算傳播功能
>
> - tools for integrating C/C++ and Fortran code
>
> 能夠跟 C/C++/Fortran 程式碼整合的工具
>
> - useful linear algebra, Fourier transform, and random number capabilities
>
> 包含線性代數、傅利葉轉換、隨機變數的功能

## 安裝

透過 `pip` 安裝 `numpy`：

```sh
pip install numpy
```

In [1]:
# import 的功能為匯入模組，在這裡我們匯入 numpy 模組
# 為了程式撰寫方便，在程式中可以用別稱來取代模組名稱
# 使用方式為 import 模組名稱 as 別稱

import numpy as np

## 陣列宣告

在 `numpy` 中陣列稱為 `ndarray`，創造陣列的語法為 `numpy.array([value1, value2, ...])`。

- 每個 `numpy.ndarray` 都有不同的**數值型態屬性** `numpy.ndarray.dtype`
    - 必須透過 `numpy.ndarray.dtype` 取得，無法透過 `type()` 取得

|`numpy` 型態|C 型態|範圍|
|-|-|-|
|`numpy.int8`|`int_8`|-128~127|
|`numpy.int16`|`int_16`|-32768~32767|
|`numpy.int32`|`int_32`|-2147483648~2147483647|
|`numpy.int64`|`int_64`|-9223372036854775808~9223372036854775807|
|`numpy.uint8`|`uint_8`|0~255|
|`numpy.uint16`|`uint_16`|0~65535|
|`numpy.uint32`|`uint_32`|0~4294967295|
|`numpy.uint64`|`uint_64`|0~18446744073709551615|
|`numpy.float32`|`float`||
|`numpy.float64`|`double`||

- 每個 `numpy.ndarray` 都有**維度屬性** `numpy.ndarray.shape`
    - `numpy.ndarray.shape` 本質是 `tuple`
    - 陣列維度愈高，`len(numpy.ndarray.shape)` 數字愈大
- 可以使用 `numpy.ndarray.reshape` 進行維度變更
    - 變更後的維度必須要與變更前的維度乘積相同
    - 變更後的內容為 **shallow copy**

In [2]:
# 陣列宣告

# 宣告 ndarray 變數
arr1 = np.array([1, 2, 3])                    
# 輸出 ndarray
print(arr1)                                   
# 輸出 True
print(type(arr1) == np.ndarray)               
# 輸出 int64
print(arr1.dtype)                             
print()

# 宣告 ndarray 變數
arr2 = np.array([1., 2., 3.])                 
# 輸出 ndarray
print(arr2)                                   
# 輸出 True
print(type(arr2) == np.ndarray)               
# 輸出 float64
print(arr2.dtype)                             
print()

# 各種 dtype
# 輸出 int8
print(np.array(arr1, dtype=np.int8).dtype)    
# 輸出 int16
print(np.array(arr1, dtype=np.int16).dtype)   
# 輸出 int32
print(np.array(arr1, dtype=np.int32).dtype)   
# 輸出 int64
print(np.array(arr1, dtype=np.int64).dtype)   
# 輸出 uint8
print(np.array(arr1, dtype=np.uint8).dtype)   
# 輸出 uint16
print(np.array(arr1, dtype=np.uint16).dtype)  
# 輸出 uint32
print(np.array(arr1, dtype=np.uint32).dtype)  
# 輸出 uint64
print(np.array(arr1, dtype=np.uint64).dtype)  
# 輸出 float32
print(np.array(arr2, dtype=np.float32).dtype) 
# 輸出 float64
print(np.array(arr2, dtype=np.float64).dtype) 

[1 2 3]
True
int32

[1. 2. 3.]
True
float64

int8
int16
int32
int64
uint8
uint16
uint32
uint64
float32
float64


In [3]:
# shape 屬性

# 宣告 ndarray 變數
arr3 = np.array([                  
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
])

# 輸出 ndarray
print(arr3)                        
# 輸出 arr3.shape (4, 3)
print(arr3.shape)                  
print()

# 重新更改 arr3.shape
print(arr3.reshape(3, 4))         
# 輸出更改後的維度 (3, 4)
print(arr3.reshape(3, 4).shape)    
print()

# 重新更改 arr3.shape
print(arr3.reshape(2, 6))          
# 輸出更改後的維度 (2, 6)
print(arr3.reshape(2, 6).shape)    
print()

# 重新更改 arr3.shape
print(arr3.reshape(2, 3, 2))       
# 輸出更改後的維度 (2, 3, 2)
print(arr3.reshape(2, 3, 2).shape) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


## 陣列取值

與 `list` 語法概念相似。

- 使用 `numpy.ndarray[位置]` 來取得 `numpy.ndarray` 中指定位置的值
    - 若為**多個維度**的陣列，則使用 `tuple` 來取得指定位置的值
    - 若位置為**負數**，則等同於反向取得指定位置的值
    - 取出的值會以 `numpy.ndarray.dtype` 的形式保留
- 使用 `numpy.ndarray[起始位置:結束位置]` 來取得 `numpy.ndarray` 中的部分**連續**值
    - **包含起始位置**的值
    - **不包含結束位置**的值
    - 取出的值會以 `numpy.ndarray` 的形式保留
- 使用 `numpy.ndarray[iterable]`（例如 `list`, `tuple` 等）來取得**多個** `numpy.ndarray` 中的值
    - 取出的值會以 `numpy.ndarray` 的形式保留
- 使用判斷式來取得 `numpy.ndarray` 中的部份資料
    - 經由判斷式所得結果也為 `numpy.ndarray`
    - 判斷式所得結果之 `numpy.ndarray.dtype` 為**布林值** `bool`（`True` 或 `False`）
    - 取出的值會以 `numpy.ndarray` 的形式保留

In [4]:
# 陣列取值

# 宣告 ndarray 變數
arr4 = np.array([   
    0, 10, 20, 30, 40, 
    50, 60, 70, 80, 90
])

# 輸出陣列 arr4 中的第 0 個位置的值 0
print(arr4[0])      
# 輸出陣列 arr4 中的第 1 個位置的值 10
print(arr4[1])      
# 輸出陣列 arr4 中的第 2 個位置的值 20
print(arr4[2])      
# 輸出陣列 arr4 中的第 -2 個位置的值 80
print(arr4[-2])     
# 輸出陣列 arr4 中的第 -1 個位置的值 90
print(arr4[-1])     
print()

# 多維陣列取值

# 宣告 ndarray 變數
arr5 = np.array([   
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
])

# 輸出陣列 arr5 中的第 0 個位置的值 [0, 1, 2]
print(arr5[0])      
# 輸出陣列 arr5 中的第 1 個位置的值 [3, 4, 5]
print(arr5[1])      
# 輸出陣列 arr5 中的第 1 個位置的值 [6, 7, 8]
print(arr5[2])      
# 輸出陣列 arr5 中的第 -2 個位置的值 [6, 7, 8]
print(arr5[-2])     
# 輸出陣列 arr5 中的第 -1 個位置的值 [9, 10, 11]
print(arr5[-1])     
print()

# 輸出陣列 arr5 中的第 [0, 0] 個位置的值 0
print(arr5[0, 0])   
# 輸出陣列 arr5 中的第 [0, 1] 個位置的值 1
print(arr5[0, 1])   
# 輸出陣列 arr5 中的第 [1, 1] 個位置的值 4
print(arr5[1, 1])   
# 輸出陣列 arr5 中的第 [1, 2] 個位置的值 5
print(arr5[1, 2])   
# 輸出陣列 arr5 中的第 [-1, -1] 個位置的值 11
print(arr5[-1, -1]) 
# 輸出陣列 arr5 中的第 [-1, -2] 個位置的值 10
print(arr5[-1, -2]) 
# 輸出陣列 arr5 中的第 [-2, -1] 個位置的值 8
print(arr5[-2, -1]) 

0
10
20
80
90

[0 1 2]
[3 4 5]
[6 7 8]
[6 7 8]
[ 9 10 11]

0
1
4
5
11
10
8


In [5]:
# 取連續值

# 宣告 ndarray 變數
arr6 = np.array([ 
    0, 10, 20, 30, 40, 
    50, 60, 70, 80, 90
])

# 輸出陣列 arr6 位置 0, 1, 2 但是不含位置 3 的值 [0, 10, 20]
print(arr6[0:3])  
# 輸出陣列 arr6 位置 7, 8, 9 的值 [70, 80, 90]
print(arr6[7:])   
# 輸出陣列 arr6 位置 0, 1 但是不含位置 2 的值 [0, 10]
print(arr6[:2])   
# 輸出陣列 arr6 所有位置的值 [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
print(arr6[:])    
print()

# 多維陣列取連續值

# 宣告 ndarray 變數
arr7 = np.array([ 
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
])

# 輸出陣列 arr7 位置 0, 1, 但是不含位置 2 的值 [[0, 1, 2], [3, 4, 5]]
print(arr7[0:2])  
print()
# 輸出陣列 arr7 位置 1, 2, 3 的值 [[3, 4, 5], [6, 7, 8], [9, 10, 11]]
print(arr7[1:])   
print()
# 輸出陣列 arr7 位置 0 但是不含位置 1 的值 [[0, 1, 2]]
print(arr7[:1])   
print()
# 輸出陣列 arr7 位置 0 但是不含位置 1 的值 [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]
print(arr7[:])    

[ 0 10 20]
[70 80 90]
[ 0 10]
[ 0 10 20 30 40 50 60 70 80 90]

[[0 1 2]
 [3 4 5]]

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[0 1 2]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
# 使用 iterable 取得多個值

# 宣告 ndarray 變數
arr8 = np.array([            
    0, 10, 20, 30, 40, 
    50, 60, 70, 80, 90
])

# 輸出陣列 arr8 中偶數位置的值 [0, 20, 40, 60, 80]
print(arr8[[0, 2, 4, 6, 8]]) 
print()
# 輸出陣列 arr8 中奇數位置的值 [10, 30, 50, 70, 90]
print(arr8[[1, 3, 5, 7, 9]]) 
print()

# 多維陣列使用 iterable 取得多個值

# 宣告 ndarray 變數
arr9 = np.array([            
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 輸出陣列 arr9[0] 與 arr9[1] 的值 [[1, 2, 3, 4] [5, 6, 7, 8]]
print(arr9[[0, 1]])          
print()
# 輸出陣列 arr9[0, 2] 與 arr9[1, 3] 的值 [3, 8]
print(arr9[[0, 1], [2, 3]])  

[ 0 20 40 60 80]

[10 30 50 70 90]

[[1 2 3 4]
 [5 6 7 8]]

[3 8]


In [7]:
# 判斷式取值

# 宣告 ndarray 變數
arr10 = np.array([            
    0, 10, 20, 30, 40, 
    50, 60, 70, 80, 90
])

# 輸出每個值是否大於 50 的 `numpy.ndarray`
print(arr10 > 50)             
# 輸出 bool
print((arr10 > 50).dtype)     
# 輸出大於 50 的值 [60, 70, 80, 90]
print(arr10[arr10 > 50])      
# 輸出除以 20 餘數為 0 的值 [0, 20, 40, 60, 80]
print(arr10[arr10 % 20 == 0]) 

[False False False False False False  True  True  True  True]
bool
[60 70 80 90]
[ 0 20 40 60 80]


## 陣列運算

### 純量運算（Scalar Operation）

對陣列內所有數值與單一純量（Scalar）進行相同計算。

|符號|意義|
|-|-|
|`numpy.ndarray + scalar`|陣列中的每個數值加上 `scalar`|
|`numpy.ndarray - scalar`|陣列中的每個數值減去 `scalar`|
|`numpy.ndarray * scalar`|陣列中的每個數值乘上 `scalar`|
|`numpy.ndarray / scalar`|陣列中的每個數值除以 `scalar`|
|`numpy.ndarray // scalar`|陣列中的每個數值除以 `scalar` 所得之商|
|`numpy.ndarray % scalar`|陣列中的每個數值除以 `scalar` 所得之餘數|
|`numpy.ndarray ** scalar`|陣列中的每個數值取 `scalar` 次方|

### 個別數值運算（Element-wised Operation）

若兩個陣列想要進行運算，則兩個陣列的**維度必須相同**（即兩陣列之 `numpy.ndarray.shape` 相同）。

|符號|意義|
|-|-|
|`A + B`|陣列 `A` 中的每個數值加上陣列 `B` 中相同位置的數值|
|`A - B`|陣列 `A` 中的每個數值減去陣列 `B` 中相同位置的數值|
|`A * B`|陣列 `A` 中的每個數值乘上陣列 `B` 中相同位置的數值|
|`A / B`|陣列 `A` 中的每個數值除以陣列 `B` 中相同位置的數值|
|`A // B`|陣列 `A` 中的每個數值除以陣列 `B` 中相同位置的數值所得之商|
|`A % B`|陣列 `A` 中的每個數值除以陣列 `B` 中相同位置的數值所得之餘數|
|`A ** B`|陣列 `A` 中的每個數值取陣列 `B` 中相同位置的數值之次方|

### 個別數值函數運算（Element-wised Functional Operation）

若想對陣列中的**所有數值**進行**相同函數運算**，必須透過 `numpy` 提供的介面進行。

|函數|意義|
|-|-|
|`numpy.sin`|陣列中的每個數值 $x$ 計算 $\sin(x)$|
|`numpy.cos`|陣列中的每個數值 $x$ 計算 $\cos(x)$|
|`numpy.tan`|陣列中的每個數值 $x$ 計算 $\tan(x)$|
|`numpy.exp`|陣列中的每個數值 $x$ 計算 $e^{x}$|
|`numpy.log`|陣列中的每個數值 $x$ 計算 $\log x$
|`numpy.ceil`|陣列中的每個數值 $x$ 計算 $\left\lceil x \right\rceil$
|`numpy.floor`|陣列中的每個數值 $x$ 計算 $\left\lfloor x \right\rfloor$

### 陣列自動擴充（Broadcasting）

若陣列 `A` 的維度為 `(a1, a2, ..., an)`（即 `A.shape == (a1, a2, ..., an)`），則陣列 `B` 在滿足以下其中一種條件時即可與陣列 `A` 進行運算：

- 陣列 `B` 與陣列 `A` 維度相同（即 `B.shape == (a1, a2, ..., an)`）
- 陣列 `B` 為純量（即 `B.shape == (1,)`）
- 陣列 `B` 的維度為 `(b1, b2, ..., bn)`，若 `ai != bi`，則 `ai == 1` 或 `bi == 1`
    - 從**最後**一個維度開始比較
    - 如果有任何一個維度無法滿足前述需求，則會得到 `ValueError`

In [8]:
# 純量運算

# 宣告 ndarray 變數
arr11 = np.array([ 
    [0, 10, 20],
    [30, 40, 50],
    [60, 70, 80],
    [90, 100, 110],
])

# 輸出陣列 arr11
print(arr11)       
print()
# 對陣列 arr11 所有數值加 5
print(arr11 + 5)   
print()
# 對陣列 arr11 所有數值減 4
print(arr11 - 4)   
print()
# 對陣列 arr11 所有數值乘 3
print(arr11 * 3)   
print()
# 對陣列 arr11 所有數值除以 10
print(arr11 / 10)  
print()
# 對陣列 arr11 所有數值除以 10 所得整數部份
print(arr11 // 10) 
print()
# 對陣列 arr11 所有數值除以 7 得到餘數
print(arr11 % 7)   
print()
# 對陣列 arr11 所有數值取 2 次方
print(arr11 ** 2)  

[[  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]]

[[  5  15  25]
 [ 35  45  55]
 [ 65  75  85]
 [ 95 105 115]]

[[ -4   6  16]
 [ 26  36  46]
 [ 56  66  76]
 [ 86  96 106]]

[[  0  30  60]
 [ 90 120 150]
 [180 210 240]
 [270 300 330]]

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[0 3 6]
 [2 5 1]
 [4 0 3]
 [6 2 5]]

[[    0   100   400]
 [  900  1600  2500]
 [ 3600  4900  6400]
 [ 8100 10000 12100]]


In [9]:
# 個別數值運算

# 宣告 ndarray 變數
arr12 = np.array([    
    [1, 2, 3],
    [4, 5, 6]
])

# 宣告 ndarray 變數
arr13 = np.array([    
    [6, 5, 4],
    [3, 2, 1]
])

# 陣列相加
print(arr12 + arr13)  
print()
# 陣列相減
print(arr12 - arr13)  
print()
# 陣列相乘
print(arr12 * arr13)  
print()
# 陣列相除
print(arr12 / arr13)  
print()
# 陣列相除取商
print(arr12 // arr13) 
print()
# 陣列相除取餘數
print(arr12 % arr13)  
print()
# 陣列 A 取陣列 B 次方
print(arr12 ** arr13) 

[[7 7 7]
 [7 7 7]]

[[-5 -3 -1]
 [ 1  3  5]]

[[ 6 10 12]
 [12 10  6]]

[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]

[[0 0 0]
 [1 2 6]]

[[1 2 3]
 [1 1 0]]

[[ 1 32 81]
 [64 25  6]]


In [10]:
# 個別數值函數運算

# 宣告 ndarray 變數
arr14 = np.array([             
    [0,     np.pi / 4,     np.pi / 2,     np.pi / 4 * 3],
    [np.pi, np.pi / 4 * 5, np.pi / 2 * 3, np.pi / 4 * 7]
])

# 陣列所有數值計算 sine
print(np.sin(arr14))           
print()
# 陣列所有數值計算 cosine
print(np.cos(arr14))           
print()
# 陣列所有數值計算 tangent
print(np.tan(arr14))           
print()

# 宣告 ndarray 變數
arr15 = np.array([             
    [1, 2, 3],
    [4, 5, 6]
])

# 陣列所有數值取指數
print(np.exp(arr15))           
print()
# 陣列所有數值取對數
print(np.log(arr15))           
print()
# 陣列所有數值取對數後無條件進位
print(np.ceil(np.log(arr15)))  
print()
# 陣列所有數值取對數後無條件捨去
print(np.floor(np.log(arr15))) 

[[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01]
 [ 1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01]]

[[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01]
 [-1.00000000e+00 -7.07106781e-01 -1.83697020e-16  7.07106781e-01]]

[[ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00]
 [-1.22464680e-16  1.00000000e+00  5.44374645e+15 -1.00000000e+00]]

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]

[[0. 1. 2.]
 [2. 2. 2.]]

[[0. 0. 1.]
 [1. 1. 1.]]


In [11]:
# 陣列自動擴充

# 宣告 ndarray 變數
arr16 = np.array([   
    [
        [1, 2],
        [3, 4],
        [5, 6],
    ],
    [
        [7, 8],
        [9 ,10],
        [11, 12]
    ]
])

# 宣告 ndarray 變數
arr17 = np.array([   
    [
        [1],
        [1],
        [1]
    ],
    [
        [2],
        [2],
        [2]
    ],
])

# 輸出陣列 arr16 維度
print(arr16.shape)   
# 輸出陣列 arr17 維度
print(arr17.shape)   
print()
# 陣列 arr16 與陣列 arr16 維度相同，所以可以直接運算
print(arr16 + arr16) 
print()
# 陣列 arr16 與陣列 arr17 可以擴充成相同維度，所以可以運算
print(arr16 + arr17) 

(2, 3, 2)
(2, 3, 1)

[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]]

[[[ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 9 10]
  [11 12]
  [13 14]]]


## 創造陣列

### 賦值（Assignment）

使用 `=` 賦與指定位置數值。可以使用 `iterable` 一次指定多個位置。

|符號|意義|
|-|-|
|`=`|賦值|
|`+=`|進行加法後賦值|
|`-=`|進行減法後賦值|
|`*=`|進行乘法後賦值|

### 隨機（Random）

創造出新的陣列，所有數值皆為**隨機決定**，必須**事先指定陣列維度**。

|函數|意義|用途|備註|
|-|-|-|-|
|`numpy.empty`|創造隨機未初始化陣列|已確認維度，尚未確認數值|無法控制隨機|
|`numpy.random.rand`|創造隨機浮點數陣列|需要隨機浮點數時|透過均勻分佈決定亂數，範圍介於 0 到 1之間|
|`numpy.random.randint`|創造隨機整數陣列|需要隨機整數時|透過均勻分佈決定亂數，可以控制隨機範圍|

### 指定數值（Filled In）

**快速創造**擁有特定數值的陣列，必須**事先指定陣列維度**。

|函數|意義|用途|
|-|-|-|
|`numpy.zeros`|創造指定維度大小的陣列，所有數值初始化為 0|快速初始化|
|`numpy.zeros_like`|複製指定陣列的維度，創造出新的陣列，所有數值初始化為 0|複製陣列並初始化|
|`numpy.ones`|創造指定維度大小的陣列，所有數值初始化為 1|快速初始化|
|`numpy.ones_like`|複製指定陣列的維度，創造出新的陣列，所有數值初始化為 1|複製陣列並初始化|
|`numpy.full`|創造指定維度大小的陣列，所有數值初始化為指定數值|快速初始化|
|`numpy.full_like`|複製指定陣列的維度，創造出新的陣列，所有數值初始化為指定數值|複製陣列並初始化|
|`numpy.eye`|創造單位矩陣|矩陣微分|
|`numpy.diag`|創造對角線矩陣，對角線初始化為指定數值|矩陣微分|
|`numpy.arange`|列舉數字|等同於 `list(range(value))`|
|`numpy.linspace`|給予起始與結束範圍，並進行線性等分|繪製圖表|
|`numpy.logspace`|給予起始與結束範圍，進行線性等分後取指數|繪製圖表|

In [12]:
# 賦值

# 宣告 ndarray 變數
arr18 = np.array([         
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
print(arr18)
print()

# 將陣列 arr18 位置 0 的所有數值改成 1995
arr18[0] = 1995            
print(arr18)
print()

# 將陣列 arr18 位置 [0, 1] 的所有數值改成 10
arr18[0, 1] = 10           
print(arr18)
print()

# 將陣列 arr18 位置 [2, 1] 與 [0, 2] 的所有數值改成 12
arr18[[2, 0], [1, 2]] = 12 
print(arr18)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1995 1995 1995]
 [   4    5    6]
 [   7    8    9]
 [  10   11   12]]

[[1995   10 1995]
 [   4    5    6]
 [   7    8    9]
 [  10   11   12]]

[[1995   10   12]
 [   4    5    6]
 [   7   12    9]
 [  10   11   12]]


In [13]:
# 宣告 ndarray 變數
arr19 = np.array([          
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
print(arr19)
print()

# 將陣列 arr19 位置 0 的所有數值加上 1995
arr19[0] += 1995            
print(arr19)
print()

# 將陣列 arr19 位置 [0, 1] 的所有數值減掉 10
arr19[0, 1] -= 10           
print(arr19)
print()

# 將陣列 arr19 位置 [2, 1] 與 [0, 2] 的所有數值乘上 12
arr19[[2, 0], [1, 2]] *= 12 
print(arr19)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1996 1997 1998]
 [   4    5    6]
 [   7    8    9]
 [  10   11   12]]

[[1996 1987 1998]
 [   4    5    6]
 [   7    8    9]
 [  10   11   12]]

[[ 1996  1987 23976]
 [    4     5     6]
 [    7    96     9]
 [   10    11    12]]


In [14]:
# 隨機

# 隨機創造維度為 (2, 3) 的陣列
# 數值為無法控制範圍的浮點數
print(np.empty((2, 3)))                      
print()                                      

# 隨機創造維度為 (2, 3) 的陣列
# 數值為介於 0 到 1 之間的浮點數
print(np.random.rand(2, 3))                  
print()                                      

# 隨機創造維度為 (2, 3) 的陣列
# 數值為介於 0 到 10 之間的浮點數
print(np.random.rand(2, 3) * 10)             
print()                                      

# 隨機創造維度為 (2, 3) 的陣列
# 數值為介於 -5 到 5 之間的浮點數
print(np.random.rand(2, 3) * 10 - 5)         
print()                                      

# 隨機創造維度為 (2, 3) 的陣列
# 數值為介於 -5 到 5 之間的整數
print(np.random.randint(-5, 5, size=(2, 3)))                                              

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]

[[0.57385695 0.0491027  0.07543303]
 [0.40107091 0.74511333 0.08265488]]

[[6.26480376 7.31483051 9.89915353]
 [0.56300764 0.5564986  3.40835813]]

[[ 4.55955067  4.76549017 -2.1453548 ]
 [ 3.13514403  3.07863121  0.7873637 ]]

[[ 2  4  0]
 [ 4 -1 -1]]


In [15]:
# 指定數值

# 創造維度為 (2, 3) 的陣列，並初始化為 0
print(np.zeros((2, 3)))        
print()

# 宣告 ndarray 變數
arr20 = np.array([             
    [1, 2, 3],
    [4, 5, 6],
])
# 複製陣列 arr20 的維度，創造出新的陣列，並初始化為 0
print(np.zeros_like(arr20))    
print()

# 創造維度為 (3, 4) 的陣列，並初始化為 1
print(np.ones((3, 4)))         
print()

# 宣告 ndarray 變數
arr21 = np.array([             
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
# 複製陣列 arr21 的維度，創造出新的陣列，並初始化為 1
print(np.ones_like(arr21))     
print()

# 創造維度為 (5, 6) 的陣列，並初始化為 420
print(np.full((5, 6), 420))    
print()

# 宣告 ndarray 變數
arr22 = np.array([             
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30]
])
# 複製陣列 arr22 的維度，創造出新的陣列，並初始化為 69
print(np.full_like(arr22, 69)) 

[[0. 0. 0.]
 [0. 0. 0.]]

[[0 0 0]
 [0 0 0]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

[[420 420 420 420 420 420]
 [420 420 420 420 420 420]
 [420 420 420 420 420 420]
 [420 420 420 420 420 420]
 [420 420 420 420 420 420]]

[[69 69 69 69 69 69]
 [69 69 69 69 69 69]
 [69 69 69 69 69 69]
 [69 69 69 69 69 69]
 [69 69 69 69 69 69]]


In [16]:
# 創造 3x3 單位矩陣
print(np.eye(3))                    
print()

# 創造 3x3 單位矩陣
# 對角線分別初始化為 8, 1, 7
print(np.diag([8, 1, 7]))           
print()                             

# 從 0 列舉至 10，但不包含 10
print(np.arange(10))                
print()

# 從 6 列舉至 9，但不包含 9
print(np.arange(6, 9))             
print()

# 從 4 遞增至 20，但不包含 20，每次遞增 7
print(np.arange(4, 20, 7))          
print()

# 將 0 到 100 切割成 9 - 1 = 8 等分
print(np.linspace(0, 100, 9))       
print()

# 將 0 到 5 切割成 4 - 1 = 3 等分
# 並將每個數字 x 變成 10 ** x
print(np.logspace(0, 5, 4))         
print()                             

# 將 1 到 6 切割成 5 - 1 = 4 等分
# 並將每個數字 x 變成 2 ** x
print(np.logspace(1, 6, 6, base=2))                                     

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[8 0 0]
 [0 1 0]
 [0 0 7]]

[0 1 2 3 4 5 6 7 8 9]

[6 7 8]

[ 4 11 18]

[  0.   12.5  25.   37.5  50.   62.5  75.   87.5 100. ]

[1.00000000e+00 4.64158883e+01 2.15443469e+03 1.00000000e+05]

[ 2.  4.  8. 16. 32. 64.]


## 矩陣運算

### 基本運算

矩陣等同於是維度為 2 的陣列。
`numpy` 提供 `numpy.matrix` 進行矩陣操作，但同樣的操作也可以直接進行在 `numpy.ndarray` 之上。

|函數|意義|
|-|-|
|`numpy.matrix`|創造矩陣|
|`numpy.transpose`|矩陣轉置|
|`numpy.dot`|矩陣乘法|
|`numpy.diag`|取出對角線|

### 進階運算

使用 `numpy.linalg` 進行線性代數中常見的計算。

|函數|意義|
|-|-|
|`numpy.linalg.inv`|反矩陣（Inverse Matrix）|
|`numpy.linalg.eig`|特徵值與特徵向量矩陣（Eigenvalues & Eigenvectors）|
|`numpy.linalg.eigvals`|特徵值矩陣（Eigenvalues）|
|`numpy.linalg.det`|行列式（Determinant）|
|`numpy.linalg.matrix_rank`|秩（Rank）|

In [17]:
# 基本運算

# 宣告 matrix 變數
mat1 = np.matrix([        
    [0, 10, 20],
    [30, 40, 50]
])

# 輸出矩陣 mat1
print(mat1)               
print()
# 輸出矩陣 mat1 轉置後的結果
print(np.transpose(mat1)) 
print()
# 輸出矩陣 mat1 轉置後的結果
print(mat1.T)             
print()

# 宣告 matrix 變數
mat2 = np.matrix(         
    np.arange(12).reshape(3, 4)
)

# 輸出矩陣 mat2
print(mat2)               
print()
# 輸出矩陣 mat1 乘上矩陣 mat2 後的結果
print(np.dot(mat1, mat2)) 
print()
# 輸出矩陣 mat1 乘上矩陣 mat2 後的結果
print(mat1.dot(mat2))     
print()

# 輸出矩陣 mat2 的對角線數值
print(np.diag(mat2))      
print()
# 輸出矩陣 mat2 的對角線數值，並保留維度
print(mat2.diagonal())    

[[ 0 10 20]
 [30 40 50]]

[[ 0 30]
 [10 40]
 [20 50]]

[[ 0 30]
 [10 40]
 [20 50]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[200 230 260 290]
 [560 680 800 920]]

[[200 230 260 290]
 [560 680 800 920]]

[ 0  5 10]

[[ 0  5 10]]


In [18]:
# 宣告 matrix 變數
mat3 = np.matrix([             
    [1, 2],
    [3, 4]
])
print(mat3)
print()

# 計算矩陣 mat3 的反矩陣
mat3_inv = np.linalg.inv(mat3) 
# 輸出矩陣 mat3 的反矩陣
print(mat3_inv)                
print()
# 計算矩陣 mat3 與其反矩陣乘積
print(mat3.dot(mat3_inv))      

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [19]:
# 宣告 matrix 變數
mat4 = np.matrix(np.diag([1, 2, 3]))           
print(mat4)
print()

# 計算矩陣 mat4 的特徵值與特徵向量
mat4_eigval, mat4_eigvec = np.linalg.eig(mat4) 
# 輸出矩陣 mat4 的特徵值
print(mat4_eigval)                             
print()
# 輸出矩陣 mat4 的特徵向量
print(mat4_eigvec)                             
print()
# 計算矩陣 mat4 的特徵值
print(np.linalg.eigvals(mat4))                 

[[1 0 0]
 [0 2 0]
 [0 0 3]]

[1. 2. 3.]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[1. 2. 3.]


In [20]:
# 宣告 matrix 變數
mat5 = np.matrix([                 
    [1, 2],
    [3, 4]
])

# 輸出矩陣 mat5 的行列式
print(np.linalg.det(mat5))         
# 輸出矩陣 mat5 的秩
print(np.linalg.matrix_rank(mat5)) 

-2.0000000000000004
2


## 維度運算

### 降維函數（Dimension Decreasing Function）

以下函數將會使**輸出**陣列維度**小於輸入**陣列維度。

|函數|意義|
|-|-|
|`numpy.sum`|將所有數值相加|
|`numpy.max`|取出所有數值中最大者|
|`numpy.min`|取出所有數值中最小者|
|`numpy.argmax`|取出所有數值中最大者的位置|
|`numpy.argmin`|取出所有數值中最小者的位置|
|`numpy.mean`|取出所有數值的平均值|
|`numpy.var`|取出所有數值的變異數|
|`numpy.std`|取出所有數值的標準差|
|`numpy.squeeze`|移除數字為 1 的維度|

### 增維函數（Dimension Increasing Function）

以下函數將會使**輸出**陣列維度**大於輸入**陣列維度。

|函數|意義|
|-|-|
|`numpy.concatenate`|串接多個相同維度的陣列|
|`numpy.expand_dims`|在指定的維度間增加 1 維度|

In [21]:
# 降維函數

# 宣告 ndarray 變數
arr23 = np.array([           
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 將陣列 arr23 中所有值相加
print(np.sum(arr23))         
# 將陣列 arr23 中所有值相加
print(arr23.sum())           

# 將陣列 arr23 中依照維度 0 將所有值相加
print(np.sum(arr23, axis=0)) 
# 將陣列 arr23 中依照維度 0 將所有值相加
print(arr23.sum(axis=0))     
# 將陣列 arr23 中依照維度 1 將所有值相加
print(np.sum(arr23, axis=1)) 
# 將陣列 arr23 中依照維度 1 將所有值相加
print(arr23.sum(axis=1))     

# 找出陣列 arr23 中最大值
print(np.max(arr23))         
# 找出陣列 arr23 中最大值
print(arr23.max())           

# 依照維度 0 找出陣列 arr23 中最大值
print(np.max(arr23, axis=0)) 
# 依照維度 0 找出陣列 arr23 中最大值
print(arr23.max(axis=0))     
# 依照維度 1 找出陣列 arr23 中最大值
print(np.max(arr23, axis=1)) 
# 依照維度 1 找出陣列 arr23 中最大值
print(arr23.max(axis=1))     

# 找出陣列 arr23 中最小值
print(np.min(arr23))         
# 找出陣列 arr23 中最小值
print(arr23.min())           

# 依照維度 0 找出陣列 arr23 中最小值
print(np.min(arr23, axis=0)) 
# 依照維度 0 找出陣列 arr23 中最小值
print(arr23.min(axis=0))     
# 依照維度 1 找出陣列 arr23 中最小值
print(np.min(arr23, axis=1)) 
# 依照維度 1 找出陣列 arr23 中最小值
print(arr23.min(axis=1))     

78
78
[15 18 21 24]
[15 18 21 24]
[10 26 42]
[10 26 42]
12
12
[ 9 10 11 12]
[ 9 10 11 12]
[ 4  8 12]
[ 4  8 12]
1
1
[1 2 3 4]
[1 2 3 4]
[1 5 9]
[1 5 9]


In [22]:
# 宣告 ndarray 變數
arr24 = np.array([              
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 找出陣列 arr24 中最大值的位置
print(np.argmax(arr24))         
# 找出陣列 arr24 中最大值的位置
print(arr24.argmax())           

# 依照維度 0 找出陣列 arr24 中最大值的位置
print(np.argmax(arr24, axis=0)) 
# 依照維度 0 找出陣列 arr24 中最大值的位置
print(arr24.argmax(axis=0))     
# 依照維度 1 找出陣列 arr24 中最大值的位置
print(np.argmax(arr24, axis=1)) 
# 依照維度 1 找出陣列 arr24 中最大值的位置
print(arr24.argmax(axis=1))     

# 找出陣列 arr24 中最小值的位置
print(np.argmin(arr24))         
# 找出陣列 arr24 中最小值的位置
print(arr24.argmin())           

# 依照維度 0 找出陣列 arr24 中最小值的位置
print(np.argmin(arr24, axis=0)) 
# 依照維度 0 找出陣列 arr24 中最小值的位置
print(arr24.argmin(axis=0))     
# 依照維度 1 找出陣列 arr24 中最小值的位置
print(np.argmin(arr24, axis=1)) 
# 依照維度 1 找出陣列 arr24 中最小值的位置
print(arr24.argmin(axis=1))     

11
11
[2 2 2 2]
[2 2 2 2]
[3 3 3]
[3 3 3]
0
0
[0 0 0 0]
[0 0 0 0]
[0 0 0]
[0 0 0]


In [23]:
# 宣告 ndarray 變數
arr25 = np.array([            
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 計算陣列 arr25 中所有值的平均數
print(np.mean(arr25))         
# 計算陣列 arr25 中所有值的平均數
print(arr25.mean())           

# 依照維度 0 計算陣列 arr25 中所有值的平均數
print(np.mean(arr25, axis=0)) 
# 依照維度 0 計算陣列 arr25 中所有值的平均數
print(arr25.mean(axis=0))     
# 依照維度 1 計算陣列 arr25 中所有值的平均數
print(np.mean(arr25, axis=1)) 
# 依照維度 1 計算陣列 arr25 中所有值的平均數
print(arr25.mean(axis=1))     

# 計算陣列 arr25 中所有值的變異數
print(np.var(arr25))          
# 計算陣列 arr25 中所有值的變異數
print(arr25.var())            

# 依照維度 0 計算陣列 arr25 中所有值的變異數
print(np.var(arr25, axis=0))  
# 依照維度 0 計算陣列 arr25 中所有值的變異數
print(arr25.var(axis=0))      
# 依照維度 1 計算陣列 arr25 中所有值的變異數
print(np.var(arr25, axis=1))  
# 依照維度 1 計算陣列 arr25 中所有值的變異數
print(arr25.var(axis=1))      

# 計算陣列 arr25 中所有值的標準差
print(np.std(arr25))          
# 計算陣列 arr25 中所有值的標準差
print(arr25.std())            

# 依照維度 0 計算陣列 arr25 中所有值的標準差
print(np.std(arr25, axis=0))  
# 依照維度 0 計算陣列 arr25 中所有值的標準差
print(arr25.std(axis=0))      
# 依照維度 1 計算陣列 arr25 中所有值的標準差
print(np.std(arr25, axis=1))  
# 依照維度 1 計算陣列 arr25 中所有值的標準差
print(arr25.std(axis=1))      

6.5
6.5
[5. 6. 7. 8.]
[5. 6. 7. 8.]
[ 2.5  6.5 10.5]
[ 2.5  6.5 10.5]
11.916666666666666
11.916666666666666
[10.66666667 10.66666667 10.66666667 10.66666667]
[10.66666667 10.66666667 10.66666667 10.66666667]
[1.25 1.25 1.25]
[1.25 1.25 1.25]
3.452052529534663
3.452052529534663
[3.26598632 3.26598632 3.26598632 3.26598632]
[3.26598632 3.26598632 3.26598632 3.26598632]
[1.11803399 1.11803399 1.11803399]
[1.11803399 1.11803399 1.11803399]


In [24]:
# 宣告 ndarray 變數
arr26 = np.array([           
    [1, 2, 3]
])

# 移除陣列 arr26 中多餘的維度
arr26_sq = np.squeeze(arr26) 

# 輸出陣列 arr26
print(arr26)                 
# 輸出陣列 arr26 的維度
print(arr26.shape)           
# 輸出移除維度後的陣列 arr26
print(arr26_sq)              
# 輸出移除維度後陣列 arr26 的維度
print(arr26_sq.shape)        

[[1 2 3]]
(1, 3)
[1 2 3]
(3,)


In [25]:
# 增維函數

# 宣告 ndarray 變數
arr27 = np.array([                       
    [1, 2, 3]
])

# 串接多個陣列 arr27
arr27_cat = np.concatenate([             
    arr27,
    arr27,
    arr27,
    arr27
]) 

# 輸出串接後的陣列 arr27_cat
print(arr27_cat)                         
# 輸出串接後的陣列 arr27_cat 維度
print(arr27_cat.shape)                   

# 宣告 ndarray 變數
arr28 = np.array([                       
    [1, 2, 3],
    [4, 5, 6]
])

print(arr28)
print(arr28.shape)

# 對陣列 arr28 維度 0 增加 1 維
arr28_ex = np.expand_dims(arr28, axis=0) 

# 輸出陣列 arr28 維度 0 增加 1 維後的結果
print(arr28_ex)                          
# 輸出陣列 arr28 維度 0 增加 1 維後的維度
print(arr28_ex.shape)                    

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
(4, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


## 練習

### 練習 1：softmax 函數

實作 Deep Learning 中常用的機率輸出函數 softmax。

若當前任務為 $c$ 分類問題，輸入資料 $D$ 經過神經網路計算後得到的 logits 為 $x \in R^c$，則分類 $i$ 的 logits $x_i$ 經過 softmax 得到的結果 $p_i$ 為：

$$
p_i = \text{softmax}(x_i) = \frac{e^{x_i}}{\sum_{j = 1}^c e^{x_j}}
$$

### 練習 2：Linear Layer + ReLU Activation

實作 Deep Learning 中線性神經網路與常用的激發函數（Activation Function）ReLU。

令當前神經網路權重（Weight）為 $W \in R^{d_{out} \times d_{in}}$，偏差值（Bias）為 $b \in R^{d_{out}}$。
若神經網路輸入值為 $x \in R^{d_{in}}$，則輸出值 $y \in R^{d_{out}}$ 為：

$$
y = \text{ReLU}(Wx + b) = \max(0, Wx + b)
$$

In [26]:
# 練習 1 解答

# 設定總共類別
c = 10                    
# 模擬輸出 logits
x = np.random.rand(c)     
# 計算指數
x_exp = np.exp(x)         
# 取得 softmax 分母
x_exp_sum = np.sum(x_exp) 
# 定義機率值維度，儲存 softmax 結果
p = np.zeros_like(x)      

# 對每個維度計算 softmax
for i in range(c):        
    p[i] = x_exp[i] / x_exp_sum

# 輸出 logits
print(x)                  
# 輸出經過 softmax 後的機率值
print(p)                  

[0.18556619 0.37905318 0.28123642 0.31880951 0.66826776 0.62849401
 0.77047729 0.66071466 0.55261746 0.06347925]
[0.0748182  0.09078991 0.08232966 0.08548189 0.12123887 0.11651139
 0.13428606 0.12032659 0.10799797 0.06621945]


In [27]:
# 練習 2 解答

# 設定輸入維度
d_in = 10                                
# 設定輸出維度
d_out = 30                               

# 模擬神經網路輸入
x = np.ones((d_in, 1))                   
# 模擬神經網路權重
W = np.random.rand(d_out, d_in) * 10 - 5 
# 模擬神經網路偏差值
b = np.random.rand(d_out, 1) * 10 - 5    

h = W.dot(x) + b
# 計算 ReLU 得到神經網路輸出
y = h * (h > 0)                          

# 輸出神經網路輸入
print(x)                                 
# 輸出神經網路輸出
print(y)                                 

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[ 8.12466747]
 [22.94626713]
 [-0.        ]
 [21.07975608]
 [ 0.19121892]
 [-0.        ]
 [-0.        ]
 [ 7.89387239]
 [ 6.53735986]
 [-0.        ]
 [11.60203612]
 [ 8.90281231]
 [-0.        ]
 [-0.        ]
 [ 6.41048415]
 [ 4.00540008]
 [ 3.14642955]
 [-0.        ]
 [-0.        ]
 [ 1.39275307]
 [ 6.40680228]
 [-0.        ]
 [-0.        ]
 [14.9703348 ]
 [ 0.68570105]
 [ 3.01057134]
 [-0.        ]
 [ 6.4081938 ]
 [10.79230041]
 [-0.        ]]
